{{ config(materialized='semantic_view', schema='SEMANTIC') }}

TABLES(
    people AS {{ ref('fct_mhsds_person_summary') }}
        PRIMARY KEY (person_id) COMMENT = 'One identifiable MHSDS person, current evidence summary',
    referrals AS {{ ref('fct_mhsds_referral_summary') }}
        PRIMARY KEY (source_record_id) COMMENT = 'One recorded referral with access measures',
    contacts AS {{ ref('fct_mhsds_care_contact') }}
        PRIMARY KEY (source_record_id) COMMENT = 'One latest referral/contact pair, all attendance states',
    spells AS {{ ref('fct_mhsds_hospital_provider_spell') }}
        PRIMARY KEY (source_record_id) COMMENT = 'One recorded provider spell, before occupancy inference',
    occupancy AS {{ ref('fct_mhsds_inpatient_occupancy') }}
        PRIMARY KEY (occupancy_interval_id) COMMENT = 'One retained inferred occupancy interval',
    diagnoses AS {{ ref('fct_mhsds_diagnosis') }}
        PRIMARY KEY (diagnosis_record_id) COMMENT = 'One retained diagnosis evidence item',
    assessments AS {{ ref('fct_mhsds_assessment_observation') }}
        PRIMARY KEY (assessment_observation_id) COMMENT = 'One accepted assessment question, dimension or score occurrence',
    legal_status AS {{ ref('fct_mhsds_mental_health_act_period') }}
        PRIMARY KEY (mental_health_act_period_id) COMMENT = 'One recorded legal-status period',
    submissions AS {{ ref('dq_mhsds_provider_submission') }}
        PRIMARY KEY (provider_organisation_code, reporting_period_end_date) COMMENT = 'One provider and accepted reporting period',
    demographics AS {{ ref('dim_mhsds_person_provider_period') }}
        PRIMARY KEY (person_provider_period_id) COMMENT = 'Reporting entity dim_mhsds_person_provider_period; see model description for grain and population',
    referral_periods AS {{ ref('fct_mhsds_referral_period') }}
        PRIMARY KEY (referral_period_id) COMMENT = 'Reporting entity fct_mhsds_referral_period; see model description for grain and population',
    caseload_referrals AS {{ ref('fct_mhsds_current_caseload_referral') }}
        PRIMARY KEY (referral_period_id) COMMENT = 'Reporting entity fct_mhsds_current_caseload_referral; see model description for grain and population',
    caseload_people AS {{ ref('fct_mhsds_current_caseload_person') }}
        PRIMARY KEY (caseload_person_provider_id) COMMENT = 'Reporting entity fct_mhsds_current_caseload_person; see model description for grain and population',
    rtt AS {{ ref('fct_mhsds_referral_to_treatment_period') }}
        PRIMARY KEY (referral_to_treatment_period_id) COMMENT = 'Reporting entity fct_mhsds_referral_to_treatment_period; see model description for grain and population',
    indirect_activity AS {{ ref('fct_mhsds_indirect_activity') }}
        PRIMARY KEY (indirect_activity_id) COMMENT = 'Reporting entity fct_mhsds_indirect_activity; see model description for grain and population',
    group_sessions AS {{ ref('fct_mhsds_group_session') }}
        PRIMARY KEY (group_session_id) COMMENT = 'Reporting entity fct_mhsds_group_session; see model description for grain and population',
    group_therapy AS {{ ref('fct_mhsds_group_therapy_contact') }}
        PRIMARY KEY (group_therapy_contact_id) COMMENT = 'Reporting entity fct_mhsds_group_therapy_contact; see model description for grain and population',
    drop_ins AS {{ ref('fct_mhsds_drop_in_contact') }}
        PRIMARY KEY (drop_in_contact_id) COMMENT = 'Reporting entity fct_mhsds_drop_in_contact; see model description for grain and population',
    accommodation AS {{ ref('fct_mhsds_accommodation_observation') }}
        PRIMARY KEY (accommodation_observation_id) COMMENT = 'Reporting entity fct_mhsds_accommodation_observation; see model description for grain and population',
    employment AS {{ ref('fct_mhsds_employment_observation') }}
        PRIMARY KEY (employment_observation_id) COMMENT = 'Reporting entity fct_mhsds_employment_observation; see model description for grain and population',
    disability AS {{ ref('fct_mhsds_disability_observation') }}
        PRIMARY KEY (disability_observation_id) COMMENT = 'Reporting entity fct_mhsds_disability_observation; see model description for grain and population',
    social_circumstances AS {{ ref('fct_mhsds_social_circumstance_observation') }}
        PRIMARY KEY (social_circumstance_observation_id) COMMENT = 'Reporting entity fct_mhsds_social_circumstance_observation; see model description for grain and population',
    care_plans AS {{ ref('fct_mhsds_care_plan_period') }}
        PRIMARY KEY (care_plan_period_id) COMMENT = 'Reporting entity fct_mhsds_care_plan_period; see model description for grain and population',
    care_plan_agreements AS {{ ref('fct_mhsds_care_plan_agreement') }}
        PRIMARY KEY (care_plan_agreement_id) COMMENT = 'Reporting entity fct_mhsds_care_plan_agreement; see model description for grain and population',
    complaints AS {{ ref('fct_mhsds_presenting_complaint') }}
        PRIMARY KEY (presenting_complaint_id) COMMENT = 'Reporting entity fct_mhsds_presenting_complaint; see model description for grain and population',
    assessment_instances AS {{ ref('fct_mhsds_assessment_instance') }}
        PRIMARY KEY (assessment_instance_id) COMMENT = 'Reporting entity fct_mhsds_assessment_instance; see model description for grain and population',
    score_changes AS {{ ref('fct_mhsds_assessment_score_change') }}
        PRIMARY KEY (assessment_score_change_id) COMMENT = 'Reporting entity fct_mhsds_assessment_score_change; see model description for grain and population',
    ctos AS {{ ref('fct_mhsds_community_treatment_order') }}
        PRIMARY KEY (community_treatment_order_id) COMMENT = 'Reporting entity fct_mhsds_community_treatment_order; see model description for grain and population',
    recalls AS {{ ref('fct_mhsds_community_treatment_order_recall') }}
        PRIMARY KEY (community_treatment_order_recall_id) COMMENT = 'Reporting entity fct_mhsds_community_treatment_order_recall; see model description for grain and population',
    restrictive_incidents AS {{ ref('fct_mhsds_restrictive_intervention_incident') }}
        PRIMARY KEY (restrictive_intervention_incident_id) COMMENT = 'Reporting entity fct_mhsds_restrictive_intervention_incident; see model description for grain and population',
    restrictive_types AS {{ ref('fct_mhsds_restrictive_intervention_type') }}
        PRIMARY KEY (restrictive_intervention_type_id) COMMENT = 'Reporting entity fct_mhsds_restrictive_intervention_type; see model description for grain and population',
    home_leave AS {{ ref('fct_mhsds_home_leave') }}
        PRIMARY KEY (home_leave_id) COMMENT = 'Reporting entity fct_mhsds_home_leave; see model description for grain and population',
    leave AS {{ ref('fct_mhsds_leave_of_absence') }}
        PRIMARY KEY (leave_of_absence_id) COMMENT = 'Reporting entity fct_mhsds_leave_of_absence; see model description for grain and population',
    awol AS {{ ref('fct_mhsds_absence_without_leave') }}
        PRIMARY KEY (absence_without_leave_id) COMMENT = 'Reporting entity fct_mhsds_absence_without_leave; see model description for grain and population',
    spell_commissioners AS {{ ref('fct_mhsds_spell_commissioner_period') }}
        PRIMARY KEY (spell_commissioner_period_id) COMMENT = 'Reporting entity fct_mhsds_spell_commissioner_period; see model description for grain and population',
    readiness AS {{ ref('fct_mhsds_discharge_readiness_period') }}
        PRIMARY KEY (discharge_readiness_period_id) COMMENT = 'Reporting entity fct_mhsds_discharge_readiness_period; see model description for grain and population',
    ward_capacity AS {{ ref('fct_mhsds_ward_capacity_period') }}
        PRIMARY KEY (ward_capacity_period_id) COMMENT = 'Reporting entity fct_mhsds_ward_capacity_period; see model description for grain and population',
    latest_provider_caseload AS {{ ref('fct_mhsds_latest_provider_caseload_referral') }}
        PRIMARY KEY (referral_period_id) COMMENT = 'Latest reported open referrals per provider, including stale periods'
)

RELATIONSHIPS(
    referrals (person_id) REFERENCES people,
    contacts (person_id) REFERENCES people,
    spells (person_id) REFERENCES people,
    occupancy (person_id) REFERENCES people,
    diagnoses (person_id) REFERENCES people,
    assessments (person_id) REFERENCES people,
    legal_status (person_id) REFERENCES people,
    referral_periods (person_id) REFERENCES people,
    referral_periods (person_provider_period_id) REFERENCES demographics,
    caseload_referrals (person_id) REFERENCES people,
    caseload_referrals (person_provider_period_id) REFERENCES demographics,
    caseload_people (person_id) REFERENCES people,
    caseload_people (person_provider_period_id) REFERENCES demographics,
    rtt (person_id) REFERENCES people,
    indirect_activity (person_id) REFERENCES people,
    indirect_activity (person_provider_period_id) REFERENCES demographics,
    group_therapy (person_id) REFERENCES people,
    accommodation (person_id) REFERENCES people,
    employment (person_id) REFERENCES people,
    disability (person_id) REFERENCES people,
    social_circumstances (person_id) REFERENCES people,
    care_plans (person_id) REFERENCES people,
    care_plans (person_provider_period_id) REFERENCES demographics,
    care_plan_agreements (person_id) REFERENCES people,
    complaints (person_id) REFERENCES people,
    assessment_instances (person_id) REFERENCES people,
    score_changes (person_id) REFERENCES people,
    ctos (person_id) REFERENCES people,
    recalls (person_id) REFERENCES people,
    restrictive_incidents (person_id) REFERENCES people,
    restrictive_types (person_id) REFERENCES people,
    home_leave (person_id) REFERENCES people,
    leave (person_id) REFERENCES people,
    awol (person_id) REFERENCES people,
    spell_commissioners (person_id) REFERENCES people,
    readiness (person_id) REFERENCES people
)

DIMENSIONS(
    people.person_id AS person_id COMMENT = 'MHSDS person key for aggregate cohort linkage only. Never return identifiers in final output.',
    people.sk_patient_id AS sk_patient_id COMMENT = 'Cross-system pseudonymised patient key. May be null. Aggregate each cohort before cross-view joins; never return identifiers.',
    people.as_of_date AS as_of_date COMMENT = 'Latest accepted dataset period, not the run date or evidence that all providers are current.',
    people.person_last_evidence_date AS last_evidence_reporting_period_end_date COMMENT = 'Latest period attached to retained person evidence.',
    people.is_current_inpatient AS is_current_inpatient COMMENT = 'Current inferred occupancy under the established recency/overlap rules.',
    people.is_currently_detained AS is_currently_detained COMMENT = 'Current detention under the documented open, expiry and submission-recency rule.',
    people.has_recorded_detention AS has_recorded_detention COMMENT = 'Any recorded detention evidence, not lifetime completeness.',
    people.is_looked_after_child AS is_looked_after_child COMMENT = 'Latest submitted indicator; null for unknown.',
    people.has_primary_diagnosis_evidence AS n_primary_diagnosis_records > 0 COMMENT = 'Recorded primary diagnosis evidence, not a clinically current diagnosis.',
    people.has_recent_attended_contact AS n_attended_contacts_12m > 0 COMMENT = 'Attended contact within the bounded 12-month window ending at as_of_date.',
    referrals.referrals_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    referrals.referrals_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    contacts.contacts_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    contacts.contacts_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    spells.spells_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    spells.spells_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    occupancy.occupancy_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    occupancy.occupancy_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    diagnoses.diagnoses_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    diagnoses.diagnoses_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    assessments.assessments_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    assessments.assessments_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    legal_status.legal_status_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    legal_status.legal_status_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    submissions.submissions_provider_code AS provider_organisation_code COMMENT = 'Provider code belonging to this entity.',
    submissions.submissions_provider_name AS provider_organisation_name COMMENT = 'Authoritative provider name where available.',
    referrals.referral_received_date AS referral_received_date COMMENT = 'Recorded referral receipt date.',
    referrals.recorded_referral_status AS referral_status COMMENT = 'Open means no recorded rejection or discharge. It is not an active caseload definition.',
    referrals.referral_primary_team_type AS primary_service_or_team_type_description COMMENT = 'Recorded primary team type, not the currency-selected service type.',
    referrals.referral_reason AS primary_reason_for_referral_description COMMENT = 'Recorded reason label.',
    referrals.referral_priority AS clinical_response_priority_description COMMENT = 'Recorded priority label.',
    referrals.referral_age AS age_at_referral COMMENT = 'Source age at referral; source special values remain visible.',
    contacts.contact_date AS care_contact_date COMMENT = 'Recorded contact date; cancelled contacts retain their scheduled date.',
    contacts.contact_team_type AS service_or_team_type_description COMMENT = 'Team type resolved within the contact submission: explicit contact team, otherwise the v6 primary referral team.',
    contacts.contact_team_id AS service_or_team_id COMMENT = 'Provider-qualified team identifier resolved within the contact submission.',
    contacts.contact_team_attribution_basis AS service_or_team_attribution_basis COMMENT = 'Explicit additional or legacy contact team, same-submission v6 primary referral team, or unresolved.',
    contacts.contact_referral_received_date AS same_submission_referral_received_date COMMENT = 'Referral receipt recorded in the contact submission, not the latest referral revision.',
    contacts.contact_same_submission_referral_linked AS is_same_submission_referral_linked COMMENT = 'Whether the referral is present in the contact submission.',
    contacts.contact_same_submission_person_consistent AS is_same_submission_referral_person_consistent COMMENT = 'Contact and same-submission referral person IDs agree; null if either identity is missing.',
    contacts.contact_latest_referral_person_consistent AS is_latest_referral_person_consistent COMMENT = 'Comparison with latest referral identity. False can reflect a later national person-ID change, not a wrong patient.',
    referrals.referral_has_contact_person_disagreement AS has_contact_referral_person_disagreement COMMENT = 'At least one contact has a different person ID from the latest referral; counts and intervals still follow the stable referral key.',
    contacts.contact_attendance AS attendance_status_description COMMENT = 'Recorded attendance label.',
    contacts.is_attended AS is_attended COMMENT = 'Attendance 05 or 06; null when missing.',
    contacts.contact_medium AS consultation_mechanism_description COMMENT = 'Recorded delivery mechanism.',
    contacts.contact_age AS age_at_care_contact COMMENT = 'Source age at contact.',
    spells.recorded_admission_date AS admission_date COMMENT = 'Recorded spell admission date.',
    spells.recorded_discharge_date AS discharge_date COMMENT = 'Missing discharge does not establish current occupancy.',
    occupancy.occupancy_admission_date AS admission_date COMMENT = 'Admission date of the retained interval.',
    occupancy.occupancy_end_date AS occupancy_end_date COMMENT = 'Derived interval end; null when retained as open.',
    occupancy.occupancy_end_reason AS occupancy_end_reason COMMENT = 'Recorded discharge, inferred last submission or supersession, or open.',
    occupancy.occupancy_is_current AS is_current_inpatient COMMENT = 'Whether the interval remains open under the retained occupancy rules.',
    occupancy.occupancy_evidence_date AS occupancy_evidence_as_of_date COMMENT = 'Maximum staged spell reporting period used by occupancy rules.',
    diagnoses.diagnosis_role AS diagnosis_role COMMENT = 'Previous, provisional, primary or secondary recorded diagnosis.',
    diagnoses.diagnosis_code AS diagnosis_code COMMENT = 'Source code; interpret with its coding scheme.',
    diagnoses.diagnosis_description AS diagnosis_description COMMENT = 'Authoritative label if available.',
    diagnoses.diagnosis_scheme AS coding_scheme_description COMMENT = 'Source coding system.',
    diagnoses.diagnosis_recorded_at AS diagnosis_recorded_at COMMENT = 'Recorded time, or discussion time for previous diagnoses. Never a claim of clinical currency.',
    assessments.assessment_concept_code AS assessment_concept_code COMMENT = 'Assessment question or observable code. Distinguish concepts before interpreting scores.',
    assessments.assessment_concept_description AS assessment_concept_description COMMENT = 'Authoritative assessment concept label.',
    assessments.assessment_tool AS assessment_tool_name COMMENT = 'Tool label where identified.',
    assessments.assessment_recorded_at AS assessment_recorded_at COMMENT = 'Supported observation time, including inherited activity timing.',
    assessments.assessment_response_status AS assessment_response_status COMMENT = 'Existing response interpretation. Observations are not completed questionnaires or outcomes.',
    legal_status.legal_status_description AS legal_status_description COMMENT = 'Authoritative legal-status label.',
    legal_status.legal_status_start_date AS legal_status_start_date COMMENT = 'Recorded period start.',
    legal_status.is_detention_period AS is_detention_period COMMENT = 'Existing project code classification.',
    legal_status.is_current_detention_period AS is_current_detention_period COMMENT = 'Existing open, unexpired and recent-submission rule.',
    submissions.submission_period_end AS reporting_period_end_date COMMENT = 'Accepted reporting period, not clinical event date.',
    submissions.is_latest_provider_period AS is_latest_provider_period COMMENT = 'Select true for one current freshness row per provider.',
    submissions.provider_months_behind_dataset AS provider_months_behind_dataset COMMENT = 'Relative freshness only; not proof of an incomplete submission.',
    demographics.demographics_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    demographics.demographics_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    demographics.demographics_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    demographics.demographics_ethnicity AS ethnicity_2001_description COMMENT = 'Entity-specific ethnicity; interpret using its reporting model definition',
    demographics.demographics_gender_identity AS gender_identity_description COMMENT = 'Entity-specific gender identity; interpret using its reporting model definition',
    demographics.demographics_imd_2019_decile AS residence_imd_2019_decile COMMENT = 'Entity-specific imd 2019 decile; interpret using its reporting model definition',
    demographics.demographics_imd_2025_decile AS residence_imd_2025_decile COMMENT = 'Entity-specific imd 2025 decile; interpret using its reporting model definition',
    demographics.demographics_age_at_period_end AS source_age_at_period_end COMMENT = 'Entity-specific age at period end; interpret using its reporting model definition',
    referral_periods.referral_periods_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    referral_periods.referral_periods_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    referral_periods.referral_periods_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    referral_periods.referral_periods_access_state AS recorded_access_state COMMENT = 'Entity-specific access state; interpret using its reporting model definition',
    referral_periods.referral_periods_open_at_period_end AS is_recorded_open_at_period_end COMMENT = 'Entity-specific open at period end; interpret using its reporting model definition',
    referral_periods.referral_periods_waiting_for_first_attendance AS is_open_without_recorded_attendance COMMENT = 'Entity-specific waiting for first attendance; interpret using its reporting model definition',
    referral_periods.referral_periods_primary_team AS primary_service_or_team_type_description COMMENT = 'Entity-specific primary team; interpret using its reporting model definition',
    caseload_referrals.caseload_referrals_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    caseload_referrals.caseload_referrals_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    caseload_referrals.caseload_referrals_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    caseload_referrals.caseload_referrals_contact_state AS recorded_caseload_contact_state COMMENT = 'Entity-specific contact state; interpret using its reporting model definition',
    caseload_referrals.caseload_referrals_provider_months_behind AS provider_months_behind_dataset COMMENT = 'Entity-specific provider months behind; interpret using its reporting model definition',
    caseload_referrals.caseload_referrals_primary_team AS primary_service_or_team_type_description COMMENT = 'Entity-specific primary team; interpret using its reporting model definition',
    caseload_people.caseload_people_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    caseload_people.caseload_people_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    caseload_people.caseload_people_evidence_date AS evidence_date COMMENT = 'Entity-specific evidence date; interpret using its reporting model definition',
    caseload_people.caseload_people_provider_months_behind AS provider_months_behind_dataset COMMENT = 'Entity-specific provider months behind; interpret using its reporting model definition',
    rtt.rtt_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    rtt.rtt_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    rtt.rtt_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    rtt.rtt_status AS rtt_status_description COMMENT = 'Entity-specific status; interpret using its reporting model definition',
    rtt.rtt_measurement_type AS waiting_time_measurement_type_description COMMENT = 'Entity-specific measurement type; interpret using its reporting model definition',
    rtt.rtt_start_date AS rtt_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    rtt.rtt_end_date AS rtt_end_date COMMENT = 'Entity-specific end date; interpret using its reporting model definition',
    indirect_activity.indirect_activity_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    indirect_activity.indirect_activity_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    indirect_activity.indirect_activity_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    indirect_activity.indirect_activity_activity_date AS indirect_activity_date COMMENT = 'Entity-specific activity date; interpret using its reporting model definition',
    indirect_activity.indirect_activity_team_type AS service_or_team_type_description COMMENT = 'Entity-specific team type; interpret using its reporting model definition',
    indirect_activity.indirect_activity_person_consulted AS person_consulted_description COMMENT = 'Entity-specific person consulted; interpret using its reporting model definition',
    indirect_activity.indirect_activity_procedure AS procedure_description COMMENT = 'Entity-specific procedure; interpret using its reporting model definition',
    group_sessions.group_sessions_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    group_sessions.group_sessions_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    group_sessions.group_sessions_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    group_sessions.group_sessions_session_date AS group_session_date COMMENT = 'Entity-specific session date; interpret using its reporting model definition',
    group_sessions.group_sessions_session_type AS group_session_type_description COMMENT = 'Entity-specific session type; interpret using its reporting model definition',
    group_sessions.group_sessions_team_type AS service_or_team_type_description COMMENT = 'Entity-specific team type; interpret using its reporting model definition',
    group_therapy.group_therapy_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    group_therapy.group_therapy_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    group_therapy.group_therapy_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    group_therapy.group_therapy_contact_date AS care_contact_date COMMENT = 'Entity-specific contact date; interpret using its reporting model definition',
    group_therapy.group_therapy_attendance AS attendance_status_description COMMENT = 'Entity-specific attendance; interpret using its reporting model definition',
    group_therapy.group_therapy_team_type AS service_or_team_type_description COMMENT = 'Entity-specific team type; interpret using its reporting model definition',
    group_therapy.group_therapy_is_attended AS is_attended COMMENT = 'Entity-specific is attended; interpret using its reporting model definition',
    drop_ins.drop_ins_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    drop_ins.drop_ins_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    drop_ins.drop_ins_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    drop_ins.drop_ins_contact_date AS contact_date COMMENT = 'Entity-specific contact date; interpret using its reporting model definition',
    drop_ins.drop_ins_outcome AS contact_outcome_description COMMENT = 'Entity-specific outcome; interpret using its reporting model definition',
    accommodation.accommodation_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    accommodation.accommodation_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    accommodation.accommodation_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    accommodation.accommodation_status AS legacy_accommodation_status_description COMMENT = 'Entity-specific status; interpret using its reporting model definition',
    accommodation.accommodation_type AS accommodation_type_description COMMENT = 'Entity-specific type; interpret using its reporting model definition',
    accommodation.accommodation_type_label_basis AS accommodation_type_label_basis COMMENT = 'Whether the type label comes from the current or legacy code list, or remains missing or unmatched',
    accommodation.accommodation_settled AS settled_accommodation_description COMMENT = 'Entity-specific settled; interpret using its reporting model definition',
    employment.employment_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    employment.employment_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    employment.employment_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    employment.employment_status AS employment_status_description COMMENT = 'Entity-specific status; interpret using its reporting model definition',
    employment.employment_label_status AS employment_status_label_status COMMENT = 'Distinguishes labelled, missing and unmatched employment codes',
    employment.employment_contract_type AS employment_contract_type_description COMMENT = 'Entity-specific contract type; interpret using its reporting model definition',
    employment.employment_recorded_date AS employment_status_recorded_date COMMENT = 'Entity-specific recorded date; interpret using its reporting model definition',
    disability.disability_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    disability.disability_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    disability.disability_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    disability.disability_type AS disability_description COMMENT = 'Entity-specific type; interpret using its reporting model definition',
    disability.disability_impact AS disability_impact_description COMMENT = 'Entity-specific impact; interpret using its reporting model definition',
    social_circumstances.social_circumstances_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    social_circumstances.social_circumstances_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    social_circumstances.social_circumstances_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    social_circumstances.social_circumstances_circumstance AS circumstance_description COMMENT = 'Entity-specific circumstance; interpret using its reporting model definition',
    care_plans.care_plans_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    care_plans.care_plans_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    care_plans.care_plans_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    care_plans.care_plans_type AS care_plan_type_description COMMENT = 'Entity-specific type; interpret using its reporting model definition',
    care_plans.care_plans_creation_date AS creation_date COMMENT = 'Entity-specific creation date; interpret using its reporting model definition',
    care_plan_agreements.care_plan_agreements_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    care_plan_agreements.care_plan_agreements_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    care_plan_agreements.care_plan_agreements_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    care_plan_agreements.care_plan_agreements_family_involvement AS family_involvement_description COMMENT = 'Entity-specific family involvement; interpret using its reporting model definition',
    complaints.complaints_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    complaints.complaints_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    complaints.complaints_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    complaints.complaints_complaint AS complaint_description COMMENT = 'Entity-specific complaint; interpret using its reporting model definition',
    complaints.complaint_code AS complaint_code COMMENT = 'Submitted complaint code; interpret with the declared finding scheme',
    complaints.finding_scheme AS finding_scheme_description COMMENT = 'Declared finding coding scheme, which may itself be incorrect in the source',
    complaints.complaint_label_status AS clinical_label_status COMMENT = 'Whether the complaint code matches the declared finding scheme',
    complaints.has_alternative_scheme_match AS has_alternative_diagnosis_scheme_match COMMENT = 'Possible source coding-namespace discrepancy; lexical overlap does not prove a source error',
    complaints.alternative_scheme AS alternative_diagnosis_coding_scheme COMMENT = 'Unconfirmed alternative coding scheme; never substitute automatically',
    complaints.alternative_complaint AS alternative_diagnosis_scheme_code_description COMMENT = 'Unconfirmed alternative label; retain the declared-scheme interpretation',
    complaints.complaints_recorded_date AS complaint_recorded_date COMMENT = 'Entity-specific recorded date; interpret using its reporting model definition',
    assessment_instances.assessment_instances_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    assessment_instances.assessment_instances_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    assessment_instances.assessment_instances_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    assessment_instances.assessment_instances_tool AS assessment_tool_name COMMENT = 'Entity-specific tool; interpret using its reporting model definition',
    assessment_instances.assessment_instances_recorded_at AS assessment_recorded_at COMMENT = 'Entity-specific recorded at; interpret using its reporting model definition',
    assessment_instances.assessment_instances_identity_basis AS instance_identity_basis COMMENT = 'Entity-specific identity basis; interpret using its reporting model definition',
    assessment_instances.assessment_instances_ambiguous_concepts AS has_repeated_or_missing_concepts COMMENT = 'Entity-specific ambiguous concepts; interpret using its reporting model definition',
    score_changes.score_changes_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    score_changes.score_changes_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    score_changes.score_changes_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    score_changes.score_changes_tool AS assessment_tool_name COMMENT = 'Entity-specific tool; interpret using its reporting model definition',
    score_changes.score_changes_concept_code AS assessment_concept_code COMMENT = 'Entity-specific concept code; interpret using its reporting model definition',
    score_changes.score_changes_concept AS assessment_concept_description COMMENT = 'Entity-specific concept; interpret using its reporting model definition',
    score_changes.score_changes_recorded_at AS assessment_recorded_at COMMENT = 'Entity-specific recorded at; interpret using its reporting model definition',
    score_changes.score_changes_has_recorded_assessor AS has_recorded_assessor COMMENT = 'Entity-specific has recorded assessor; interpret using its reporting model definition',
    ctos.ctos_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    ctos.ctos_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    ctos.ctos_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    ctos.ctos_start_date AS order_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    ctos.ctos_end_date AS order_end_date COMMENT = 'Entity-specific end date; interpret using its reporting model definition',
    ctos.ctos_end_reason AS order_end_reason_description COMMENT = 'Entity-specific end reason; interpret using its reporting model definition',
    recalls.recalls_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    recalls.recalls_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    recalls.recalls_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    recalls.recalls_start_date AS recall_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    recalls.recalls_end_date AS recall_end_date COMMENT = 'Entity-specific end date; interpret using its reporting model definition',
    restrictive_incidents.restrictive_incidents_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    restrictive_incidents.restrictive_incidents_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    restrictive_incidents.restrictive_incidents_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    restrictive_incidents.restrictive_incidents_reason AS incident_reason_description COMMENT = 'Entity-specific reason; interpret using its reporting model definition',
    restrictive_incidents.restrictive_incidents_start_date AS incident_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    restrictive_types.restrictive_types_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    restrictive_types.restrictive_types_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    restrictive_types.restrictive_types_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    restrictive_types.restrictive_types_type AS intervention_type_description COMMENT = 'Entity-specific type; interpret using its reporting model definition',
    restrictive_types.restrictive_types_patient_injury AS patient_injury_description COMMENT = 'Entity-specific patient injury; interpret using its reporting model definition',
    restrictive_types.restrictive_types_start_date AS intervention_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    home_leave.home_leave_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    home_leave.home_leave_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    home_leave.home_leave_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    home_leave.home_leave_start_date AS leave_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    home_leave.home_leave_end_date AS leave_end_date COMMENT = 'Entity-specific end date; interpret using its reporting model definition',
    leave.leave_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    leave.leave_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    leave.leave_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    leave.leave_start_date AS leave_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    leave.leave_end_reason AS leave_end_reason_description COMMENT = 'Entity-specific end reason; interpret using its reporting model definition',
    awol.awol_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    awol.awol_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    awol.awol_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    awol.awol_start_date AS leave_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    awol.awol_end_reason AS leave_end_reason_description COMMENT = 'Entity-specific end reason; interpret using its reporting model definition',
    spell_commissioners.spell_commissioners_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    spell_commissioners.spell_commissioners_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    spell_commissioners.spell_commissioners_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    spell_commissioners.spell_commissioners_commissioner AS commissioner_organisation_name COMMENT = 'Entity-specific commissioner; interpret using its reporting model definition',
    spell_commissioners.spell_commissioners_start_date AS commissioner_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    readiness.readiness_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    readiness.readiness_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    readiness.readiness_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    readiness.readiness_delay_reason AS delay_reason_description COMMENT = 'Entity-specific delay reason; interpret using its reporting model definition',
    readiness.readiness_attribution AS delay_attribution_description COMMENT = 'Entity-specific attribution; interpret using its reporting model definition',
    readiness.readiness_start_date AS readiness_start_date COMMENT = 'Entity-specific start date; interpret using its reporting model definition',
    readiness.readiness_end_date AS readiness_end_date COMMENT = 'Entity-specific end date; interpret using its reporting model definition',
    ward_capacity.ward_capacity_provider_code AS provider_organisation_code COMMENT = 'Entity-specific provider code; interpret using its reporting model definition',
    ward_capacity.ward_capacity_provider_name AS provider_organisation_name COMMENT = 'Entity-specific provider name; interpret using its reporting model definition',
    ward_capacity.ward_capacity_period_end AS reporting_period_end_date COMMENT = 'Entity-specific period end; interpret using its reporting model definition',
    ward_capacity.ward_capacity_site AS ward_site_name COMMENT = 'Entity-specific site; interpret using its reporting model definition',
    ward_capacity.ward_capacity_setting AS ward_setting_description COMMENT = 'Entity-specific setting; interpret using its reporting model definition',
    ward_capacity.ward_capacity_age_group AS ward_intended_age_group_description COMMENT = 'Entity-specific age group; interpret using its reporting model definition',
    ward_capacity.ward_capacity_security_level AS ward_security_level_description COMMENT = 'Entity-specific security level; interpret using its reporting model definition',
    ward_capacity.ward_capacity_has_capacity AS has_reported_available_capacity COMMENT = 'Entity-specific has capacity; interpret using its reporting model definition',
    ward_capacity.ward_capacity_has_stay_evidence AS has_matching_ward_stay_evidence COMMENT = 'Entity-specific has stay evidence; interpret using its reporting model definition',
    people.has_current_recorded_caseload AS has_current_recorded_caseload COMMENT = 'Open referral evidence in the dataset latest reporting month, including community care and waiting for attendance',
    latest_provider_caseload.latest_provider_caseload_provider AS provider_organisation_name COMMENT = 'Provider name',
    latest_provider_caseload.latest_provider_caseload_evidence_date AS reporting_period_end_date COMMENT = 'Provider latest reporting date, which may be old',
    latest_provider_caseload.latest_provider_caseload_months_behind AS provider_months_behind_dataset COMMENT = 'Calendar months behind the dataset reporting date'
)

METRICS(
    people.person_count AS COUNT(people.person_id) COMMENT = 'Distinct recorded MHSDS person IDs in all modelled evidence, including clinical-only records. National ID changes can split an individual across rows.',
    people.current_inpatient_person_count AS COUNT_IF(people.is_current_inpatient) COMMENT = 'People with inferred current occupancy evidence.',
    people.currently_detained_person_count AS COUNT_IF(people.is_currently_detained) COMMENT = 'People meeting the unchanged detention-currentness rule.',
    referrals.referral_count AS COUNT(referrals.source_record_id) COMMENT = 'Recorded referrals, including those without person identity.',
    referrals.referral_person_count AS COUNT(DISTINCT referrals.person_id) COMMENT = 'Distinct recorded MHSDS person IDs with selected referrals; not a reconciled longitudinal patient count.',
    referrals.mean_days_to_first_attended_contact AS AVG(referrals.days_to_first_attended_contact) COMMENT = 'Mean over referrals with a valid recorded interval. Excludes unobserved waits; not target compliance.',
    referrals.referrals_with_observed_first_attendance AS COUNT(referrals.days_to_first_attended_contact) COMMENT = 'Denominator for the observed mean interval.',
    contacts.contact_count AS COUNT(contacts.source_record_id) COMMENT = 'All recorded contact attendance states.',
    contacts.attended_contact_count AS COUNT_IF(contacts.is_attended) COMMENT = 'Recorded attended contacts.',
    contacts.dna_contact_count AS COUNT_IF(contacts.is_dna) COMMENT = 'Recorded DNA contacts.',
    contacts.cancelled_contact_count AS COUNT_IF(contacts.is_cancelled) COMMENT = 'Recorded cancelled contacts.',
    contacts.contact_person_count AS COUNT(DISTINCT contacts.person_id) COMMENT = 'Distinct recorded MHSDS person IDs with selected contacts. IDs can change over time; do not add monthly distinct counts.',
    spells.recorded_spell_count AS COUNT(spells.source_record_id) COMMENT = 'Recorded provider spells before occupancy inference.',
    occupancy.occupancy_interval_count AS COUNT(occupancy.occupancy_interval_id) COMMENT = 'Retained inferred intervals, not recorded provider spells.',
    occupancy.current_occupancy_count AS COUNT_IF(occupancy.is_current_inpatient) COMMENT = 'Retained intervals classified as open.',
    diagnoses.diagnosis_record_count AS COUNT(diagnoses.diagnosis_record_id) COMMENT = 'Retained diagnosis records, not distinct conditions or current diagnoses.',
    diagnoses.diagnosis_person_count AS COUNT(DISTINCT diagnoses.person_id) COMMENT = 'Distinct recorded MHSDS person IDs with selected diagnosis evidence; IDs can change over time.',
    assessments.assessment_observation_count AS COUNT(assessments.assessment_observation_id) COMMENT = 'Accepted question, dimension or score occurrences; not completed questionnaires.',
    assessments.scored_observation_count AS COUNT(assessments.assessment_score_numeric) COMMENT = 'Observations with an interpreted numeric score, not outcomes or improvement.',
    legal_status.legal_status_period_count AS COUNT(legal_status.mental_health_act_period_id) COMMENT = 'Recorded periods across all statuses.',
    submissions.accepted_submission_count AS SUM(submissions.n_accepted_submissions) COMMENT = 'Accepted files for selected provider periods.',
    submissions.submitted_referral_row_count AS SUM(submissions.n_referral_source_records) COMMENT = 'Submitted referral records, not new referrals in the period.',
    submissions.submitted_contact_row_count AS SUM(submissions.n_contact_source_records) COMMENT = 'Submitted contact records, not event-date activity.',
    demographics.person_provider_period_count AS COUNT(demographics.person_provider_period_id) COMMENT = 'Count at the documented dim_mhsds_person_provider_period grain; repeated period evidence is not new events',
    referral_periods.referral_period_count AS COUNT(referral_periods.referral_period_id) COMMENT = 'Count at the documented fct_mhsds_referral_period grain; repeated period evidence is not new events',
    caseload_referrals.current_caseload_referral_count AS COUNT(caseload_referrals.referral_period_id) COMMENT = 'Count at the documented fct_mhsds_current_caseload_referral grain; repeated period evidence is not new events',
    caseload_people.current_caseload_person_provider_count AS COUNT(caseload_people.caseload_person_provider_id) COMMENT = 'Count at the documented fct_mhsds_current_caseload_person grain; repeated period evidence is not new events',
    rtt.rtt_evidence_count AS COUNT(rtt.referral_to_treatment_period_id) COMMENT = 'Count at the documented fct_mhsds_referral_to_treatment_period grain; repeated period evidence is not new events',
    indirect_activity.indirect_activity_count AS COUNT(indirect_activity.indirect_activity_id) COMMENT = 'Count at the documented fct_mhsds_indirect_activity grain; repeated period evidence is not new events',
    group_sessions.group_session_count AS COUNT(group_sessions.group_session_id) COMMENT = 'Count at the documented fct_mhsds_group_session grain; repeated period evidence is not new events',
    group_therapy.group_therapy_contact_count AS COUNT(group_therapy.group_therapy_contact_id) COMMENT = 'Count at the documented fct_mhsds_group_therapy_contact grain; repeated period evidence is not new events',
    drop_ins.drop_in_contact_count AS COUNT(drop_ins.drop_in_contact_id) COMMENT = 'Count at the documented fct_mhsds_drop_in_contact grain; repeated period evidence is not new events',
    accommodation.accommodation_evidence_count AS COUNT(accommodation.accommodation_observation_id) COMMENT = 'Count at the documented fct_mhsds_accommodation_observation grain; repeated period evidence is not new events',
    employment.employment_evidence_count AS COUNT(employment.employment_observation_id) COMMENT = 'Count at the documented fct_mhsds_employment_observation grain; repeated period evidence is not new events',
    disability.disability_evidence_count AS COUNT(disability.disability_observation_id) COMMENT = 'Count at the documented fct_mhsds_disability_observation grain; repeated period evidence is not new events',
    social_circumstances.social_circumstance_evidence_count AS COUNT(social_circumstances.social_circumstance_observation_id) COMMENT = 'Count at the documented fct_mhsds_social_circumstance_observation grain; repeated period evidence is not new events',
    care_plans.care_plan_snapshot_count AS COUNT(care_plans.care_plan_period_id) COMMENT = 'Count at the documented fct_mhsds_care_plan_period grain; repeated period evidence is not new events',
    care_plan_agreements.care_plan_agreement_count AS COUNT(care_plan_agreements.care_plan_agreement_id) COMMENT = 'Count at the documented fct_mhsds_care_plan_agreement grain; repeated period evidence is not new events',
    complaints.presenting_complaint_count AS COUNT(complaints.presenting_complaint_id) COMMENT = 'Count at the documented fct_mhsds_presenting_complaint grain; repeated period evidence is not new events',
    assessment_instances.assessment_instance_count AS COUNT(assessment_instances.assessment_instance_id) COMMENT = 'Count at the documented fct_mhsds_assessment_instance grain; repeated period evidence is not new events',
    score_changes.score_change_pair_count AS COUNT(score_changes.assessment_score_change_id) COMMENT = 'Count at the documented fct_mhsds_assessment_score_change grain; repeated period evidence is not new events',
    ctos.community_treatment_order_count AS COUNT(ctos.community_treatment_order_id) COMMENT = 'Count at the documented fct_mhsds_community_treatment_order grain; repeated period evidence is not new events',
    recalls.cto_recall_count AS COUNT(recalls.community_treatment_order_recall_id) COMMENT = 'Count at the documented fct_mhsds_community_treatment_order_recall grain; repeated period evidence is not new events',
    restrictive_incidents.restrictive_incident_count AS COUNT(restrictive_incidents.restrictive_intervention_incident_id) COMMENT = 'Count at the documented fct_mhsds_restrictive_intervention_incident grain; repeated period evidence is not new events',
    restrictive_types.restrictive_type_count AS COUNT(restrictive_types.restrictive_intervention_type_id) COMMENT = 'Count at the documented fct_mhsds_restrictive_intervention_type grain; repeated period evidence is not new events',
    home_leave.home_leave_period_count AS COUNT(home_leave.home_leave_id) COMMENT = 'Count at the documented fct_mhsds_home_leave grain; repeated period evidence is not new events',
    leave.leave_of_absence_period_count AS COUNT(leave.leave_of_absence_id) COMMENT = 'Count at the documented fct_mhsds_leave_of_absence grain; repeated period evidence is not new events',
    awol.absence_without_leave_count AS COUNT(awol.absence_without_leave_id) COMMENT = 'Count at the documented fct_mhsds_absence_without_leave grain; repeated period evidence is not new events',
    spell_commissioners.spell_commissioner_period_count AS COUNT(spell_commissioners.spell_commissioner_period_id) COMMENT = 'Count at the documented fct_mhsds_spell_commissioner_period grain; repeated period evidence is not new events',
    readiness.discharge_readiness_period_count AS COUNT(readiness.discharge_readiness_period_id) COMMENT = 'Count at the documented fct_mhsds_discharge_readiness_period grain; repeated period evidence is not new events',
    ward_capacity.ward_capacity_period_count AS COUNT(ward_capacity.ward_capacity_period_id) COMMENT = 'Count at the documented fct_mhsds_ward_capacity_period grain; repeated period evidence is not new events',
    caseload_people.current_caseload_person_count AS COUNT(DISTINCT caseload_people.person_id) COMMENT = 'Distinct people across selected providers; provider counts must not be added',
    caseload_referrals.caseload_referrals_without_attendance AS COUNT_IF(caseload_referrals.is_open_without_recorded_attendance) COMMENT = 'Current recorded open referrals with no attendance evidence by their provider period end',
    referral_periods.open_referral_period_count AS COUNT_IF(referral_periods.is_recorded_open_at_period_end) COMMENT = 'Open referral snapshots; select one reporting period for a caseload count',
    indirect_activity.recorded_indirect_activity_minutes AS SUM(indirect_activity.duration_minutes) COMMENT = 'Submitted patient-perspective minutes; inspect duration quality and repeated submission evidence',
    group_sessions.recorded_anonymous_participations AS SUM(group_sessions.recorded_participant_count) COMMENT = 'Reported anonymous participations, not unique people or linked patients',
    group_therapy.attended_group_therapy_contact_count AS COUNT_IF(group_therapy.is_attended) COMMENT = 'Attended patient contacts within group therapy, already included in all contact counts',
    score_changes.mean_score_change AS AVG(score_changes.score_change) COMMENT = 'Mean current-minus-previous score only within one selected assessment concept and instrument; no clinical direction is asserted',
    score_changes.mean_previous_score AS AVG(score_changes.previous_score) COMMENT = 'Paired previous-score mean; require one selected assessment concept',
    score_changes.mean_current_score AS AVG(score_changes.current_score) COMMENT = 'Paired current-score mean; require one selected assessment concept',
    ward_capacity.reported_available_bed_days AS SUM(ward_capacity.available_bed_days) COMMENT = 'Reported available staffed bed days, occupied or unoccupied; null capacity stays unknown',
    ward_capacity.reported_closed_bed_days AS SUM(ward_capacity.temporarily_closed_bed_days) COMMENT = 'Reported temporarily closed staffed bed days',
    ward_capacity.recorded_ward_stay_midnight_count AS SUM(ward_capacity.recorded_ward_stay_midnights) COMMENT = 'Recorded interval midnights, including leave and possible overlaps; not physical occupancy',
    latest_provider_caseload.latest_provider_open_referral_count AS COUNT(latest_provider_caseload.referral_period_id) COMMENT = 'Latest provider open-referral evidence, including stale submissions; not current dataset-month caseload'
)

COMMENT = 'MHSDS recorded care and current evidence. Each metric retains its declared entity grain. General reporting is independent of currency classifications.'
AI_SQL_GENERATION 'Choose the entity matching the question. Recorded spells differ from inferred occupancy. For current recorded caseload use caseload_referrals or caseload_people at the dataset latest reporting month; use latest_provider_caseload for older provider evidence; first attended contact intervals are descriptive, not national waiting standards. Diagnosis records are not current diagnoses, assessment observations are not completed questionnaires, and descriptive score changes do not establish clinical improvement. Keep assessment changes within a single concept and instrument. Use event dates for activity and submission periods for freshness. Person current-state dimensions describe the latest feed and must not be applied as historical state. Filtering on person attributes restricts analysis to identifiable people. For cross-entity cohorts, reduce each fact to the intended person or referral grain before joining. Never multiply contacts through staff or team relationships. Contact and referral person IDs can change between submissions. Use same-submission context for historical team attribution and inspect latest-referral person consistency before interpreting cross-entity person cohorts. Return aggregates only, never person or patient identifiers. Use demographics for period-matched age, ethnicity and deprivation through supported temporal relationships. Group therapy contacts are a subset of contacts and have no definitive shared session identifier; anonymous group sessions and drop-ins cannot link to people. Capacity is monthly staffed bed-day evidence; recorded ward-stay midnights include leave and can have incomplete commissioning extract coverage. Do not present their ratio as live or validated physical occupancy. Currency classification and costing are separate models.'
AI_QUESTION_CATEGORIZATION 'Use for MHSDS referral access, attendance and service activity, recorded admissions, inferred current occupancy, recorded diagnoses, assessment observations, legal-status periods, person summaries and submission freshness. Use current recorded caseload, historical referral state, indirect and group activity, circumstances, care plans, descriptive assessment changes, restrictions and ward capacity. Do not claim clinical improvement, national waiting-time compliance or real-time bed occupancy.'
