{{
    config(
        description='Generated raw pass-through for DATA_LAKE.SUS_AE.EncounterDenormalised_DateRange.'
    )
}}

select
    "SK_EncounterID" as sk_encounter_id
    , "dv_Extract_Type" as dv_extract_type
    , "dv_Query_ID" as dv_query_id
    , "dv_FinYear" as dv_fin_year
    , "dv_FinMonth" as dv_fin_month
    , "dv_Activity_Period_Date" as dv_activity_period_date
    , "CDS_Record_Type" as cds_record_type
    , "Generated_Record_ID" as generated_record_id
    , "Spell_Identifier" as spell_identifier
    , "Unique_CDS_Identifier" as unique_cds_identifier
    , "EM_Attendance_Number" as em_attendance_number
    , "Arrival_Date" as arrival_date
    , "Arrival_Time" as arrival_time
    , "EM_Referral_Source" as em_referral_source
    , "EM_Mode_of_Arrival" as em_mode_of_arrival
    , "EM_Department_Type" as em_department_type
    , "EM_Attendance_Category" as em_attendance_category
    , "EM_Incident_Location_Type" as em_incident_location_type
    , "EM_Patient_Group" as em_patient_group
    , "EM_Staff_Member_Code" as em_staff_member_code
    , "dv_EM_Initial_Assessment_Date" as dv_em_initial_assessment_date
    , "EM_Initial_Assessment_Time" as em_initial_assessment_time
    , "EM_Time_Seen_for_Treatment" as em_time_seen_for_treatment
    , "dv_EM_Date_Seen_for_Treatment" as dv_em_date_seen_for_treatment
    , "dv_EM_Attendance_Conclusion_Date" as dv_em_attendance_conclusion_date
    , "EM_Attendance_Conclusion_Time" as em_attendance_conclusion_time
    , "EM_Attendance_Disposal" as em_attendance_disposal
    , "EM_Departure_Date" as em_departure_date
    , "EM_Departure_Time" as em_departure_time
    , "dv_EM_Conclusion_Waiting_Time" as dv_em_conclusion_waiting_time
    , "EM_Duration_Time" as em_duration_time
    , "dv_EM_Treatment_Wait_Time" as dv_em_treatment_wait_time
    , "Number_Diagnosis" as number_diagnosis
    , "Number_Procedures" as number_procedures
    , "SK_PatientID" as sk_patient_id
    , "DW_NHS_Number" as dw_nhs_number
    , "CCG_NHS_Number" as ccg_nhs_number
    , "Local_Patient_Identifier" as local_patient_identifier
    , "Carer_Support_Indicator" as carer_support_indicator
    , "Ethnic_Category_Code" as ethnic_category_code
    , "Age_At_CDS_Activity_Date" as age_at_cds_activity_date
    , "Gender_Code" as gender_code
    , "Postcode_of_Usual_Address" as postcode_of_usual_address
    , "dv_LSOA" as dv_lsoa
    , "Registered_GMP_Code_Original_Data" as registered_gmp_code_original_data
    , "GP_Practice_Code" as gp_practice_code
    , "GP_Practice_Code_Original_Data" as gp_practice_code_original_data
    , "Provider_Reference_No" as provider_reference_no
    , "Commissioner_Reference_No" as commissioner_reference_no
    , "Commissioning_Serial_No_Agreement_No" as commissioning_serial_no_agreement_no
    , "NHS_Service_Agreement_Line_No" as nhs_service_agreement_line_no
    , "Organisation_Code_Code_of_Provider" as organisation_code_code_of_provider
    , "Provider_Site_Code" as provider_site_code
    , "Organisation_Code_Code_of_Commissioner" as organisation_code_code_of_commissioner
    , "Organisation_Code_PCT_of_Residence" as organisation_code_pct_of_residence
    , "PCT_Derived_from_GP_Practice" as pct_derived_from_gp_practice
    , "Patient_Postcode_Derived_PCT" as patient_postcode_derived_pct
    , "PCT_of_Residence_Original" as pct_of_residence_original
    , "PCT_Responsible" as pct_responsible
    , "dv_CCAM_SWL" as dv_ccam_swl
    , "dv_Commissioner_Code_of_Residence" as dv_commissioner_code_of_residence
    , "dv_Purchaser_ID" as dv_purchaser_id
    , "dv_Contract_Suffix" as dv_contract_suffix
    , "dv_CostMethodDescription" as dv_cost_method_description
    , "Core_HRG" as core_hrg
    , "dv_HRG" as dv_hrg
    , "dv_Local_Cost_Code" as dv_local_cost_code
    , "dv_Reason_for_Difference" as dv_reason_for_difference
    , "dv_IsPBR" as dv_is_pbr
    , "dv_Base_Cost" as dv_base_cost
    , "dv_MFF_Index_Applied" as dv_mff_index_applied
    , "Tariff_Initial_Amount_National" as tariff_initial_amount_national
    , "Tariff_Pre_MFF_Adjusted_National" as tariff_pre_mff_adjusted_national
    , "Applied_MFF_National" as applied_mff_national
    , "Tariff_Total_Payment_National" as tariff_total_payment_national
    , "PBR_Final_Tariff" as pbr_final_tariff
    , "dv_Total_Cost_Inc_MFF" as dv_total_cost_inc_mff
    , "EM_Diagnosis_First" as em_diagnosis_first
    , "EM_Diagnosis_Second_1" as em_diagnosis_second_1
    , "EM_Diagnosis_Second_2" as em_diagnosis_second_2
    , "EM_Diagnosis_Second_3" as em_diagnosis_second_3
    , "EM_Diagnosis_Second_4" as em_diagnosis_second_4
    , "EM_Diagnosis_Second_5" as em_diagnosis_second_5
    , "EM_Diagnosis_Second_6" as em_diagnosis_second_6
    , "EM_Diagnosis_Second_7" as em_diagnosis_second_7
    , "EM_Diagnosis_Second_8" as em_diagnosis_second_8
    , "EM_Diagnosis_Second_9" as em_diagnosis_second_9
    , "EM_Diagnosis_Second_10" as em_diagnosis_second_10
    , "EM_Diagnosis_Second_11" as em_diagnosis_second_11
    , "EM_Diagnosis_Second_12" as em_diagnosis_second_12
    , "EM_Investigation_First" as em_investigation_first
    , "EM_Investigation_Second_1" as em_investigation_second_1
    , "EM_Investigation_Second_2" as em_investigation_second_2
    , "EM_Investigation_Second_3" as em_investigation_second_3
    , "EM_Investigation_Second_4" as em_investigation_second_4
    , "EM_Investigation_Second_5" as em_investigation_second_5
    , "EM_Investigation_Second_6" as em_investigation_second_6
    , "EM_Investigation_Second_7" as em_investigation_second_7
    , "EM_Investigation_Second_8" as em_investigation_second_8
    , "EM_Investigation_Second_9" as em_investigation_second_9
    , "EM_Investigation_Second_10" as em_investigation_second_10
    , "EM_Investigation_Second_11" as em_investigation_second_11
    , "EM_Investigation_Second_12" as em_investigation_second_12
    , "EM_Treatment_First" as em_treatment_first
    , "EM_Treatment_Second_1" as em_treatment_second_1
    , "EM_Treatment_Second_2" as em_treatment_second_2
    , "EM_Treatment_Second_3" as em_treatment_second_3
    , "EM_Treatment_Second_4" as em_treatment_second_4
    , "EM_Treatment_Second_5" as em_treatment_second_5
    , "EM_Treatment_Second_6" as em_treatment_second_6
    , "EM_Treatment_Second_7" as em_treatment_second_7
    , "EM_Treatment_Second_8" as em_treatment_second_8
    , "EM_Treatment_Second_9" as em_treatment_second_9
    , "EM_Treatment_Second_10" as em_treatment_second_10
    , "EM_Treatment_Second_11" as em_treatment_second_11
    , "EM_Treatment_Second_12" as em_treatment_second_12
from {{ source('sus_ae_monthly', 'EncounterDenormalised_DateRange') }}
