{{
    config(
        description='Generated raw pass-through for DATA_LAKE.SUS_IP.EncounterDenormalised_DateRange.'
    )
}}

select
    "SK_EncounterID" as sk_encounter_id
    , "dv_Extract_Type" as dv_extract_type
    , "dv_Query_ID" as dv_query_id
    , "dv_FinYear" as dv_fin_year
    , "dv_FinMonth" as dv_fin_month
    , "dv_Activity_Period_Date" as dv_activity_period_date
    , "Generated_Record_ID" as generated_record_id
    , "Spell_Identifier" as spell_identifier
    , "Unique_CDS_Identifier" as unique_cds_identifier
    , "Hospital_Provider_Spell_No" as hospital_provider_spell_no
    , "Referrer_Code" as referrer_code
    , "Referring_Organisation_Code" as referring_organisation_code
    , "Organisation_Code_Patient_Pathway_Identifier" as organisation_code_patient_pathway_identifier
    , "RTT_Patient_Pathway_Identifier" as rtt_patient_pathway_identifier
    , "RTT_Period_End_Date" as rtt_period_end_date
    , "RTT_Period_Start_Date" as rtt_period_start_date
    , "dv_RTT_Length_Derived" as dv_rtt_length_derived
    , "RTT_Status" as rtt_status
    , "Decided_To_Admit_Date" as decided_to_admit_date
    , "Episode_Start_Date" as episode_start_date
    , "Episode_End_Date" as episode_end_date
    , "dv_EpisodeGrossLengthOfStay" as dv_episode_gross_length_of_stay
    , "Episode_Number" as episode_number
    , "Last_Episode_in_Spell_Indicator" as last_episode_in_spell_indicator
    , "Start_Date_Hospital_Provider_Spell" as start_date_hospital_provider_spell
    , "Start_Time_Hospital_Provider_Spell" as start_time_hospital_provider_spell
    , "End_Date_Hospital_Provider_Spell" as end_date_hospital_provider_spell
    , "Discharge_Time_Hospital_Provider_Spell" as discharge_time_hospital_provider_spell
    , "Ready_For_Discharge_Date" as ready_for_discharge_date
    , "dv_LengthOfStay_Gross" as dv_length_of_stay_gross
    , "dv_CDSActivityDate" as dv_cds_activity_date
    , "Source_of_Admission_Hospital_Provider_Spell" as source_of_admission_hospital_provider_spell
    , "Discharge_Destination_Hospital_Provider_Spell" as discharge_destination_hospital_provider_spell
    , "Discharge_Method_Hospital_Provider_Spell" as discharge_method_hospital_provider_spell
    , "Administrative_Category_on_Admission" as administrative_category_on_admission
    , "First_Regular_Day_Night_Admission" as first_regular_day_night_admission
    , "Intended_Management" as intended_management
    , "Patient_Classification" as patient_classification
    , "Admission_Method_Hospital_Provider_Spell" as admission_method_hospital_provider_spell
    , "Age_Group_Intended_at_Epiend" as age_group_intended_at_epiend
    , "Neonatal_Level_of_Care" as neonatal_level_of_care
    , "dv_NumberDiagnoses" as dv_number_diagnoses
    , "dv_NumberProcedures" as dv_number_procedures
    , "dv_NumberUnbundledHRGs" as dv_number_unbundled_hr_gs
    , "SK_PatientID" as sk_patient_id
    , "DW_NHS_Number" as dw_nhs_number
    , "CCG_NHS_Number" as ccg_nhs_number
    , "Local_Patient_Identifier" as local_patient_identifier
    , "Carer_Support_Indicator" as carer_support_indicator
    , "Ethnic_Category_Code" as ethnic_category_code
    , "Age_At_CDS_Activity_Date" as age_at_cds_activity_date
    , "Birth_Date" as birth_date
    , "dv_YearOfBirth" as dv_year_of_birth
    , "Gender_Code" as gender_code
    , "Postcode_of_Usual_Address" as postcode_of_usual_address
    , "dv_LSOACode" as dv_lsoa_code
    , "Legal_Status_Classification_Code" as legal_status_classification_code
    , "GP_Code_Original_data" as gp_code_original_data
    , "GP_Practice_Code_Original_Data" as gp_practice_code_original_data
    , "GP_Practice_Code_Derived" as gp_practice_code_derived
    , "dv_PracticeCode_Validated" as dv_practice_code_validated
    , "Provider_Reference_No" as provider_reference_no
    , "Commissioner_Reference_No" as commissioner_reference_no
    , "Commissioner_Serial_No_Agreement_No" as commissioner_serial_no_agreement_no
    , "NHS_Service_Agreement_Line_No" as nhs_service_agreement_line_no
    , "Consultant_Code" as consultant_code
    , "Main_Specialty_Code" as main_specialty_code
    , "Treatment_Function_Code" as treatment_function_code
    , "Local_Sub_Specialty_Code" as local_sub_specialty_code
    , "Ward_Code_at_Episode_Start_Date" as ward_code_at_episode_start_date
    , "Ward_Code_at_Episode_End_Date" as ward_code_at_episode_end_date
    , "dv_WardCode_At_Admission" as dv_ward_code_at_admission
    , "dv_WardCode_At_Discharge" as dv_ward_code_at_discharge
    , "dv_SpecCom_ServiceCode_National_Episode" as dv_spec_com_service_code_national_episode
    , "dv_SpecCom_ServiceCode_National_Spell" as dv_spec_com_service_code_national_spell
    , "dv_SpecCom_ServiceCode_Local_Episode" as dv_spec_com_service_code_local_episode
    , "dv_SpecCom_ServiceCode_Local_Spell" as dv_spec_com_service_code_local_spell
    , "Organisation_Code_Code_of_Provider" as organisation_code_code_of_provider
    , "Organisation_Code_Code_of_Commissioner" as organisation_code_code_of_commissioner
    , "Site_code_of_Treatment_at_start_of_episode" as site_code_of_treatment_at_start_of_episode
    , "Organisation_Code_PCT_of_Residence" as organisation_code_pct_of_residence
    , "Commissioner_Code_Original_Data" as commissioner_code_original_data
    , "PCT_Derived_from_GP_Practice" as pct_derived_from_gp_practice
    , "Patient_Postcode_Derived_PCT" as patient_postcode_derived_pct
    , "dv_CCAM_SEL" as dv_ccam_sel
    , "dv_CCAM_SWL" as dv_ccam_swl
    , "dv_Commissioner_Code_of_Residence" as dv_commissioner_code_of_residence
    , "dv_Purchaser_ID" as dv_purchaser_id
    , "dv_Contract_Suffix" as dv_contract_suffix
    , "dv_CostMethodDescription" as dv_cost_method_description
    , "Programme_Budgeting_Category" as programme_budgeting_category
    , "Core_HRG_Calculated" as core_hrg_calculated
    , "Spell_Core_HRG" as spell_core_hrg
    , "dv_HRG" as dv_hrg
    , "dv_Local_Cost_Code" as dv_local_cost_code
    , "dv_Reason_for_Difference" as dv_reason_for_difference
    , "Spell_In_Pbr_Not_In_Pbr" as spell_in_pbr_not_in_pbr
    , "dv_IsPBR" as dv_is_pbr
    , "dv_ApplicableTariff" as dv_applicable_tariff
    , "dv_Base_Cost" as dv_base_cost
    , "dv_IsShortStay" as dv_is_short_stay
    , "dv_SpecialServiceID" as dv_special_service_id
    , "dv_ServiceAdjustment_Cost" as dv_service_adjustment_cost
    , "dv_BestPracticeTariff_Code" as dv_best_practice_tariff_code
    , "dv_SpecialistPalliativeCareDays" as dv_specialist_palliative_care_days
    , "dv_RehabDays" as dv_rehab_days
    , "dv_DelayedDischargeDays" as dv_delayed_discharge_days
    , "dv_TariffType" as dv_tariff_type
    , "dv_LengthOfStay_Net" as dv_length_of_stay_net
    , "dv_ExcessBedDays" as dv_excess_bed_days
    , "dv_ExcessBedDays_Cost" as dv_excess_bed_days_cost
    , "dv_MFF_Index_Applied" as dv_mff_index_applied
    , "Pbr_Final_Tariff" as pbr_final_tariff
    , "dv_Total_Cost_Inc_MFF" as dv_total_cost_inc_mff
    , "Primary_Diagnosis_Code" as primary_diagnosis_code
    , "dv_IsSpell" as dv_is_spell
    , "Secondary_Diagnosis_Code_1" as secondary_diagnosis_code_1
    , "Secondary_Diagnosis_Code_2" as secondary_diagnosis_code_2
    , "Secondary_Diagnosis_Code_3" as secondary_diagnosis_code_3
    , "Secondary_Diagnosis_Code_4" as secondary_diagnosis_code_4
    , "Secondary_Diagnosis_Code_5" as secondary_diagnosis_code_5
    , "Secondary_Diagnosis_Code_6" as secondary_diagnosis_code_6
    , "Secondary_Diagnosis_Code_7" as secondary_diagnosis_code_7
    , "Secondary_Diagnosis_Code_8" as secondary_diagnosis_code_8
    , "Secondary_Diagnosis_Code_9" as secondary_diagnosis_code_9
    , "Secondary_Diagnosis_Code_10" as secondary_diagnosis_code_10
    , "Secondary_Diagnosis_Code_11" as secondary_diagnosis_code_11
    , "Secondary_Diagnosis_Code_12" as secondary_diagnosis_code_12
    , "Operation_Status" as operation_status
    , "Primary_Procedure_Code" as primary_procedure_code
    , "Primary_Procedure_Date" as primary_procedure_date
    , "Secondary_Procedure_Code_1" as secondary_procedure_code_1
    , "Secondary_Procedure_Date_1" as secondary_procedure_date_1
    , "Secondary_Procedure_Code_2" as secondary_procedure_code_2
    , "Secondary_Procedure_Date_2" as secondary_procedure_date_2
    , "Secondary_Procedure_Code_3" as secondary_procedure_code_3
    , "Secondary_Procedure_Date_3" as secondary_procedure_date_3
    , "Secondary_Procedure_Code_4" as secondary_procedure_code_4
    , "Secondary_Procedure_Date_4" as secondary_procedure_date_4
    , "Secondary_Procedure_Code_5" as secondary_procedure_code_5
    , "Secondary_Procedure_Date_5" as secondary_procedure_date_5
    , "Secondary_Procedure_Code_6" as secondary_procedure_code_6
    , "Secondary_Procedure_Date_6" as secondary_procedure_date_6
    , "Secondary_Procedure_Code_7" as secondary_procedure_code_7
    , "Secondary_Procedure_Date_7" as secondary_procedure_date_7
    , "Secondary_Procedure_Code_8" as secondary_procedure_code_8
    , "Secondary_Procedure_Date_8" as secondary_procedure_date_8
    , "Secondary_Procedure_Code_9" as secondary_procedure_code_9
    , "Secondary_Procedure_Date_9" as secondary_procedure_date_9
    , "Secondary_Procedure_Code_10" as secondary_procedure_code_10
    , "Secondary_Procedure_Date_10" as secondary_procedure_date_10
    , "Secondary_Procedure_Code_11" as secondary_procedure_code_11
    , "Secondary_Procedure_Date_11" as secondary_procedure_date_11
    , "Secondary_Procedure_Code_12" as secondary_procedure_code_12
    , "Secondary_Procedure_Date_12" as secondary_procedure_date_12
    , "dv_Unbundled_HRG_1" as dv_unbundled_hrg_1
    , "dv_Unbundled_HRG_2" as dv_unbundled_hrg_2
    , "dv_Unbundled_HRG_3" as dv_unbundled_hrg_3
    , "dv_Unbundled_HRG_4" as dv_unbundled_hrg_4
    , "dv_Unbundled_HRG_5" as dv_unbundled_hrg_5
    , "dv_Unbundled_HRG_6" as dv_unbundled_hrg_6
    , "dv_Unbundled_HRG_7" as dv_unbundled_hrg_7
    , "dv_Unbundled_HRG_8" as dv_unbundled_hrg_8
    , "dv_Unbundled_HRG_9" as dv_unbundled_hrg_9
    , "dv_Unbundled_HRG_10" as dv_unbundled_hrg_10
    , "dv_Unbundled_HRG_11" as dv_unbundled_hrg_11
    , "dv_Unbundled_HRG_12" as dv_unbundled_hrg_12
    , "dv_Unbundled_Days_Total" as dv_unbundled_days_total
    , "dv_Unbundled_Cost_Total" as dv_unbundled_cost_total
    , "dv_Critical_CareDay_Count" as dv_critical_care_day_count
from {{ source('sus_ip_monthly', 'EncounterDenormalised_DateRange') }}
