{{
    config(
        description='Generated raw pass-through for DATA_LAKE.SUS_OP.EncounterDenormalised_DateRange.'
    )
}}

select
    "SK_EncounterID" as sk_encounter_id
    , "dv_Extract_Type" as dv_extract_type
    , "dv_Query_ID" as dv_query_id
    , "dv_FinYear" as dv_fin_year
    , "dv_FinMonth" as dv_fin_month
    , "dv_Activity_Period_Date" as dv_activity_period_date
    , "dv_Month_at_End_Activity" as dv_month_at_end_activity
    , "Generated_Record_ID" as generated_record_id
    , "Attendance_Identifier" as attendance_identifier
    , "Spell_Identifier" as spell_identifier
    , "Unique_CDS_Identifier" as unique_cds_identifier
    , "Referrer_Code" as referrer_code
    , "Referring_Organisation_Code" as referring_organisation_code
    , "Referral_Request_Received_Date" as referral_request_received_date
    , "Priority_Type" as priority_type
    , "Service_Type_Requested" as service_type_requested
    , "Source_of_Referral_for_Outpatients" as source_of_referral_for_outpatients
    , "Is_Valid_UBRN" as is_valid_ubrn
    , "UBRN_Occurrence_Count" as ubrn_occurrence_count
    , "Organisation_Code_Patient_Pathway_Identifier" as organisation_code_patient_pathway_identifier
    , "RTT_Patient_Pathway_Identifier" as rtt_patient_pathway_identifier
    , "RTT_Period_Start_Date" as rtt_period_start_date
    , "RTT_Period_End_Date" as rtt_period_end_date
    , "dv_RTT_Length_Derived" as dv_rtt_length_derived
    , "RTT_Status" as rtt_status
    , "Appointment_Date" as appointment_date
    , "Appointment_Time" as appointment_time
    , "dv_CDSActivityDate" as dv_cds_activity_date
    , "Administrative_Category" as administrative_category
    , "First_Attendance" as first_attendance
    , "Attended_Or_Did_Not_Attend" as attended_or_did_not_attend
    , "Outcome_of_Attendance" as outcome_of_attendance
    , "Consultant_Code" as consultant_code
    , "Medical_Staff_Type_Seeing_Patient" as medical_staff_type_seeing_patient
    , "Location_Type_Code" as location_type_code
    , "SK_PatientID" as sk_patient_id
    , "DW_NHS_Number" as dw_nhs_number
    , "CCG_NHS_Number" as ccg_nhs_number
    , "Local_Patient_Identifier" as local_patient_identifier
    , "Ethnic_Category_Code" as ethnic_category_code
    , "Age" as age
    , "dv_YearOfBirth" as dv_year_of_birth
    , "Gender_Code" as gender_code
    , "Postcode_of_Usual_Address" as postcode_of_usual_address
    , "dv_LSOA" as dv_lsoa
    , "GP_Code" as gp_code
    , "GP_Practice_Code_Original_Data" as gp_practice_code_original_data
    , "GP_Practice_Code_Derived" as gp_practice_code_derived
    , "dv_PracticeCode_Validated" as dv_practice_code_validated
    , "Provider_Reference_No" as provider_reference_no
    , "Commissioner_Reference_No" as commissioner_reference_no
    , "Commissioning_Serial_No_Agreement_No" as commissioning_serial_no_agreement_no
    , "NHS_Service_Agreement_Line_No" as nhs_service_agreement_line_no
    , "Main_Specialty_Code" as main_specialty_code
    , "Treatment_Function_Code" as treatment_function_code
    , "Local_Sub_Specialty_Code" as local_sub_specialty_code
    , "Clinic_Code" as clinic_code
    , "dv_SpecCom_ServiceCode_National" as dv_spec_com_service_code_national
    , "dv_SpecCom_ServiceCode_Local" as dv_spec_com_service_code_local
    , "Spell_NPOC" as spell_npoc
    , "Organisation_Code_Code_of_Provider" as organisation_code_code_of_provider
    , "Site_code_of_Treatment" as site_code_of_treatment
    , "Organisation_Code_PCT_of_Residence" as organisation_code_pct_of_residence
    , "Patient_Postcode_Derived_PCT" as patient_postcode_derived_pct
    , "Organisation_Code_Code_of_Commissioner" as organisation_code_code_of_commissioner
    , "PCT_Derived_from_GP_Practice" as pct_derived_from_gp_practice
    , "dv_CCAM_SWL" as dv_ccam_swl
    , "dv_Commissioner_Code_of_Residence" as dv_commissioner_code_of_residence
    , "dv_Purchaser_ID" as dv_purchaser_id
    , "dv_Contract_Suffix" as dv_contract_suffix
    , "dv_CostMethodDescription" as dv_cost_method_description
    , "Core_HRG" as core_hrg
    , "dv_HRGUsedForTariff" as dv_hrg_used_for_tariff
    , "dv_HRG" as dv_hrg
    , "dv_Local_Cost_Code" as dv_local_cost_code
    , "dv_Reason_for_Difference" as dv_reason_for_difference
    , "Spell_In_PbR_Not_In_PbR" as spell_in_pb_r_not_in_pb_r
    , "dv_IsPBR" as dv_is_pbr
    , "dv_ApplicableTariff" as dv_applicable_tariff
    , "dv_Base_Cost" as dv_base_cost
    , "dv_TariffType" as dv_tariff_type
    , "dv_MFF_Index_Applied" as dv_mff_index_applied
    , "Tariff_Initial_Amount_National" as tariff_initial_amount_national
    , "Tariff_Pre_MFF_Adjusted_National" as tariff_pre_mff_adjusted_national
    , "Tariff_Total_Payment_National" as tariff_total_payment_national
    , "Pbr_Final_Tariff" as pbr_final_tariff
    , "dv_Total_Cost_Inc_MFF" as dv_total_cost_inc_mff
    , "Number_Diagnosis" as number_diagnosis
    , "Primary_Diagnosis_Code" as primary_diagnosis_code
    , "Secondary_Diagnosis_Code_1" as secondary_diagnosis_code_1
    , "Secondary_Diagnosis_Code_2" as secondary_diagnosis_code_2
    , "Secondary_Diagnosis_Code_3" as secondary_diagnosis_code_3
    , "Secondary_Diagnosis_Code_4" as secondary_diagnosis_code_4
    , "Secondary_Diagnosis_Code_5" as secondary_diagnosis_code_5
    , "Secondary_Diagnosis_Code_6" as secondary_diagnosis_code_6
    , "Secondary_Diagnosis_Code_7" as secondary_diagnosis_code_7
    , "Secondary_Diagnosis_Code_8" as secondary_diagnosis_code_8
    , "Secondary_Diagnosis_Code_9" as secondary_diagnosis_code_9
    , "Secondary_Diagnosis_Code_10" as secondary_diagnosis_code_10
    , "Secondary_Diagnosis_Code_11" as secondary_diagnosis_code_11
    , "Secondary_Diagnosis_Code_12" as secondary_diagnosis_code_12
    , "Operation_Status" as operation_status
    , "Number_Procedures" as number_procedures
    , "Primary_Procedure_Code" as primary_procedure_code
    , "Primary_Procedure_Date" as primary_procedure_date
    , "Secondary_Procedure_Code_1" as secondary_procedure_code_1
    , "Secondary_Procedure_Date_1" as secondary_procedure_date_1
    , "Secondary_Procedure_Code_2" as secondary_procedure_code_2
    , "Secondary_Procedure_Date_2" as secondary_procedure_date_2
    , "Secondary_Procedure_Code_3" as secondary_procedure_code_3
    , "Secondary_Procedure_Date_3" as secondary_procedure_date_3
    , "Secondary_Procedure_Code_4" as secondary_procedure_code_4
    , "Secondary_Procedure_Date_4" as secondary_procedure_date_4
    , "Secondary_Procedure_Code_5" as secondary_procedure_code_5
    , "Secondary_Procedure_Date_5" as secondary_procedure_date_5
    , "Secondary_Procedure_Code_6" as secondary_procedure_code_6
    , "Secondary_Procedure_Date_6" as secondary_procedure_date_6
    , "Secondary_Procedure_Code_7" as secondary_procedure_code_7
    , "Secondary_Procedure_Date_7" as secondary_procedure_date_7
    , "Secondary_Procedure_Code_8" as secondary_procedure_code_8
    , "Secondary_Procedure_Date_8" as secondary_procedure_date_8
    , "Secondary_Procedure_Code_9" as secondary_procedure_code_9
    , "Secondary_Procedure_Date_9" as secondary_procedure_date_9
    , "Secondary_Procedure_Code_10" as secondary_procedure_code_10
    , "Secondary_Procedure_Date_10" as secondary_procedure_date_10
    , "Secondary_Procedure_Code_11" as secondary_procedure_code_11
    , "Secondary_Procedure_Date_11" as secondary_procedure_date_11
    , "Secondary_Procedure_Code_12" as secondary_procedure_code_12
    , "Secondary_Procedure_Date_12" as secondary_procedure_date_12
    , "dv_Unbundled_HRG_1" as dv_unbundled_hrg_1
    , "dv_Unbundled_HRG_2" as dv_unbundled_hrg_2
    , "dv_Unbundled_HRG_3" as dv_unbundled_hrg_3
    , "dv_Unbundled_HRG_4" as dv_unbundled_hrg_4
    , "dv_Unbundled_HRG_5" as dv_unbundled_hrg_5
    , "dv_Unbundled_HRG_6" as dv_unbundled_hrg_6
    , "dv_Unbundled_HRG_7" as dv_unbundled_hrg_7
    , "dv_Unbundled_HRG_8" as dv_unbundled_hrg_8
    , "dv_Unbundled_HRG_9" as dv_unbundled_hrg_9
    , "dv_Unbundled_HRG_10" as dv_unbundled_hrg_10
    , "dv_Unbundled_HRG_11" as dv_unbundled_hrg_11
    , "dv_Unbundled_HRG_12" as dv_unbundled_hrg_12
    , "dv_Number_Unbundled_HRGs" as dv_number_unbundled_hr_gs
    , "dv_Number_Unbundled_Non_Priced_HRGs" as dv_number_unbundled_non_priced_hr_gs
    , "dv_Number_Unbundled_Priced_HRGs" as dv_number_unbundled_priced_hr_gs
from {{ source('sus_op_monthly', 'EncounterDenormalised_DateRange') }}
