{{
    config(
        description='Generated raw pass-through for DATA_LAKE.SUS_IP.PBR_Preprocess_SP_DateRange.'
    )
}}

select
    "SK_EncounterID" as sk_encounter_id
    , "SK_PatientID" as sk_patient_id
    , "SUS_Version" as sus_version
    , "Spell_Identifier" as spell_identifier
    , "Reason_Access_Provided" as reason_access_provided
    , "Org_Code_Local_Patient_Identifier" as org_code_local_patient_identifier
    , "Organisation_Code_Patient_Pathway_Identifier" as organisation_code_patient_pathway_identifier
    , "RTT_Period_End_Date" as rtt_period_end_date
    , "RTT_Period_Start_Date" as rtt_period_start_date
    , "RTT_Status" as rtt_status
    , "Age_At_CDS_Activity_Date" as age_at_cds_activity_date
    , "Age_At_Start_of_Spell" as age_at_start_of_spell
    , "Age_At_End_of_Spell" as age_at_end_of_spell
    , "Spell_Age" as spell_age
    , "Patient_Type" as patient_type
    , "Carer_Support_Indicator" as carer_support_indicator
    , "Legal_Status_Classification_Code" as legal_status_classification_code
    , "Ethnic_Category_Code" as ethnic_category_code
    , "Marital_Status" as marital_status
    , "NHS_Number_Status_Indicator" as nhs_number_status_indicator
    , "Gender_Code" as gender_code
    , "Postcode_Sector_of_Usual_Address" as postcode_sector_of_usual_address
    , "Organisation_Code_PCT_of_Residence" as organisation_code_pct_of_residence
    , "Patient_Postcode_Derived_PCT_Type" as patient_postcode_derived_pct_type
    , "Patient_Postcode_Derived_PCT" as patient_postcode_derived_pct
    , "Administrative_Category_On_Admission" as administrative_category_on_admission
    , "Patient_Classification" as patient_classification
    , "Admission_Method_Hospital_Provider_Spell" as admission_method_hospital_provider_spell
    , "Admission_Type_Derived" as admission_type_derived
    , "Admission_Subtype_Derived" as admission_subtype_derived
    , "Discharge_Destination_Hospital_Provider_Spell" as discharge_destination_hospital_provider_spell
    , "Discharge_Method_Hospital_Provider_Spell" as discharge_method_hospital_provider_spell
    , "Source_of_Admission_Hospital_Provider_Spell" as source_of_admission_hospital_provider_spell
    , "Start_Date_Hospital_Provider_Spell" as start_date_hospital_provider_spell
    , "Ready_for_Discharge_Date" as ready_for_discharge_date
    , "End_Date_Hospital_Provider_Spell" as end_date_hospital_provider_spell
    , "Spell_In_PbR/Not_In_PbR" as spell_in_pb_r_not_in_pb_r
    , "Spell_Exclusion_Reason" as spell_exclusion_reason
    , "Applicable_Costing_Period" as applicable_costing_period
    , "SHA_Commissioner" as sha_commissioner
    , "SHA_Provider" as sha_provider
    , "Organisation_Code_Code_of_Provider" as organisation_code_code_of_provider
    , "Provider_Code_Original_Data" as provider_code_original_data
    , "Provider_Site_Code" as provider_site_code
    , "Organisation_Code_Code_of_Commissioner" as organisation_code_code_of_commissioner
    , "Commissioner_Code_Original_Data" as commissioner_code_original_data
    , "PCT_Derived_from_GP_Practice" as pct_derived_from_gp_practice
    , "GP_Practice_Derived_from_PDS" as gp_practice_derived_from_pds
    , "Main_Specialty_Code" as main_specialty_code
    , "Treatment_Function_Code" as treatment_function_code
    , "GP_Code_Original_data" as gp_code_original_data
    , "GP_Practice_Code_Original_Data" as gp_practice_code_original_data
    , "GP_Practice_Code_Derived" as gp_practice_code_derived
    , "Referrer_Code" as referrer_code
    , "Referring_Organisation_Code" as referring_organisation_code
    , "Duration_of_Elective_Wait" as duration_of_elective_wait
    , "Intended_Management" as intended_management
    , "Decided_To_Admit_Date" as decided_to_admit_date
    , "Length_of_Stay_Hospital_Provider_Spell" as length_of_stay_hospital_provider_spell
    , "PbR_Final_Adjusted_Length_of_Stay" as pb_r_final_adjusted_length_of_stay
    , "Number_of_Commissioners_in_PbR_Spell" as number_of_commissioners_in_pb_r_spell
    , "Number_Diagnosis" as number_diagnosis
    , "Number_Procedures" as number_procedures
    , "Number_Unbundled_HRGs" as number_unbundled_hr_gs
    , "Number_Unbundled_Non_Priced_HRGs" as number_unbundled_non_priced_hr_gs
    , "Number_Unbundled_Priced_HRGs" as number_unbundled_priced_hr_gs
    , "Excluded_Episodes_in_Hospital_Provider_Spell" as excluded_episodes_in_hospital_provider_spell
    , "Number_SSCs" as number_ss_cs
    , "Number_BPT_Indicators" as number_bpt_indicators
    , "PbR_Spell_Trimpoint_Days" as pb_r_spell_trimpoint_days
    , "PbR_Days_Beyond_Trimpoint" as pb_r_days_beyond_trimpoint
    , "Spell_ACC_Length_Of_Stay" as spell_acc_length_of_stay
    , "Spell_NCC_Length_Of_Stay" as spell_ncc_length_of_stay
    , "Spell_PCC_Length_Of_Stay" as spell_pcc_length_of_stay
    , "Spell_Primary_Diagnosis" as spell_primary_diagnosis
    , "Spell_Dominant_Procedure" as spell_dominant_procedure
    , "Primary_Procedure_Code" as primary_procedure_code
    , "Significant_Specialised_Service_Code" as significant_specialised_service_code
    , "Specialised_Service_Code_1" as specialised_service_code_1
    , "Specialised_Service_Code_2" as specialised_service_code_2
    , "Specialised_Service_Code_3" as specialised_service_code_3
    , "Specialised_Service_Code_4" as specialised_service_code_4
    , "Specialised_Service_Code_5" as specialised_service_code_5
    , "BPT_Indicator_1" as bpt_indicator_1
    , "BPT_Indicator_1_Action" as bpt_indicator_1_action
    , "BPT_Indicator_2" as bpt_indicator_2
    , "BPT_Indicator_2_Action" as bpt_indicator_2_action
    , "BPT_Indicator_3" as bpt_indicator_3
    , "BPT_Indicator_3_Action" as bpt_indicator_3_action
    , "BPT_Indicator_4" as bpt_indicator_4
    , "BPT_Indicator_4_Action" as bpt_indicator_4_action
    , "BPT_Indicator_5" as bpt_indicator_5
    , "BPT_Indicator_5_Action" as bpt_indicator_5_action
    , "Tariff_Initial_Amount_National" as tariff_initial_amount_national
    , "Tariff_Service_Adjustment_National" as tariff_service_adjustment_national
    , "Tariff_Long_Stay_Rate_National" as tariff_long_stay_rate_national
    , "Tariff_Long_Stay_Payment_National" as tariff_long_stay_payment_national
    , "Aggregate_UnBundled_Adjustment_National" as aggregate_un_bundled_adjustment_national
    , "Applied_MFF_Elective" as applied_mff_elective
    , "Applied_MFF_Non_Elective" as applied_mff_non_elective
    , "MFF_Adjustment" as mff_adjustment
    , "Tariff_Pre_MFF_Adjusted_National" as tariff_pre_mff_adjusted_national
    , "Tariff_Total_Payment_National" as tariff_total_payment_national
    , "PbR_Final_Tariff" as pb_r_final_tariff
    , "Final_Tariff_Applied" as final_tariff_applied
    , "Grouping_Method" as grouping_method
    , "Code_Cleaning" as code_cleaning
    , "Spell_Core_HRG" as spell_core_hrg
    , "Core_HRG_Version_Calculated" as core_hrg_version_calculated
    , "Grouping_Algorithm_Version" as grouping_algorithm_version
    , "Unbundled_HRG_1" as unbundled_hrg_1
    , "Unbundled_HRG_2" as unbundled_hrg_2
    , "Unbundled_HRG_3" as unbundled_hrg_3
    , "Unbundled_HRG_4" as unbundled_hrg_4
    , "Unbundled_HRG_5" as unbundled_hrg_5
    , "Unbundled_HRG_6" as unbundled_hrg_6
    , "Unbundled_HRG_7" as unbundled_hrg_7
    , "Unbundled_HRG_8" as unbundled_hrg_8
    , "Unbundled_HRG_9" as unbundled_hrg_9
    , "Unbundled_HRG_10" as unbundled_hrg_10
    , "Unbundled_HRG_11" as unbundled_hrg_11
    , "Unbundled_HRG_12" as unbundled_hrg_12
    , "Spell_Programme_Budgeting_Category" as spell_programme_budgeting_category
    , "PbR_Spell_Error_Status" as pb_r_spell_error_status
    , "Applicable_Date" as applicable_date
    , "Extract_Date" as extract_date
    , "Spell_NPOC" as spell_npoc
    , "Spell_Service_Line" as spell_service_line
    , "CDS_Schema_Version" as cds_schema_version
    , "Prime_Recipient" as prime_recipient
    , "Copy_Recipients" as copy_recipients
    , "Derived_Commissioner" as derived_commissioner
    , "Derived_Commissioner_Type" as derived_commissioner_type
    , "_" as unnamed_field
    , "Evidence_Based_Intervention_Category" as evidence_based_intervention_category
    , "Evidence_Based_Intervention_Type" as evidence_based_intervention_type
    , "ActivityPeriod" as activity_period
from {{ source('sus_ip_monthly', 'PBR_Preprocess_SP_DateRange') }}
