{{ config(materialized='view') }}

select
    sk_encounter_id
    , sk_patient_id
    , sus_version
    , spell_identifier
    , reason_access_provided
    , org_code_local_patient_identifier
    , organisation_code_patient_pathway_identifier
    , rtt_period_end_date
    , rtt_period_start_date
    , rtt_status
    , age_at_cds_activity_date
    , age_at_start_of_spell
    , age_at_end_of_spell
    , spell_age
    , patient_type
    , carer_support_indicator
    , legal_status_classification_code
    , ethnic_category_code
    , marital_status
    , nhs_number_status_indicator
    , gender_code
    , postcode_sector_of_usual_address
    , organisation_code_pct_of_residence
    , patient_postcode_derived_pct_type
    , patient_postcode_derived_pct
    , administrative_category_on_admission
    , patient_classification
    , admission_method_hospital_provider_spell
    , admission_type_derived
    , admission_subtype_derived
    , discharge_destination_hospital_provider_spell
    , discharge_method_hospital_provider_spell
    , source_of_admission_hospital_provider_spell
    , start_date_hospital_provider_spell
    , ready_for_discharge_date
    , end_date_hospital_provider_spell
    , spell_in_pb_r_not_in_pb_r
    , spell_exclusion_reason
    , applicable_costing_period
    , sha_commissioner
    , sha_provider
    , organisation_code_code_of_provider
    , provider_code_original_data
    , provider_site_code
    , organisation_code_code_of_commissioner
    , commissioner_code_original_data
    , pct_derived_from_gp_practice
    , gp_practice_derived_from_pds
    , main_specialty_code
    , treatment_function_code
    , gp_code_original_data
    , gp_practice_code_original_data
    , gp_practice_code_derived
    , referrer_code
    , referring_organisation_code
    , duration_of_elective_wait
    , intended_management
    , decided_to_admit_date
    , length_of_stay_hospital_provider_spell
    , pb_r_final_adjusted_length_of_stay
    , number_of_commissioners_in_pb_r_spell
    , number_diagnosis
    , number_procedures
    , number_unbundled_hr_gs
    , number_unbundled_non_priced_hr_gs
    , number_unbundled_priced_hr_gs
    , excluded_episodes_in_hospital_provider_spell
    , number_ss_cs
    , number_bpt_indicators
    , pb_r_spell_trimpoint_days
    , pb_r_days_beyond_trimpoint
    , spell_acc_length_of_stay
    , spell_ncc_length_of_stay
    , spell_pcc_length_of_stay
    , spell_primary_diagnosis
    , spell_dominant_procedure
    , primary_procedure_code
    , significant_specialised_service_code
    , specialised_service_code_1
    , specialised_service_code_2
    , specialised_service_code_3
    , bpt_indicator_1
    , bpt_indicator_1_action
    , tariff_initial_amount_national
    , tariff_service_adjustment_national
    , tariff_long_stay_rate_national
    , tariff_long_stay_payment_national
    , aggregate_un_bundled_adjustment_national
    , applied_mff_elective
    , applied_mff_non_elective
    , mff_adjustment
    , tariff_pre_mff_adjusted_national
    , tariff_total_payment_national
    , pb_r_final_tariff
    , final_tariff_applied
    , grouping_method
    , code_cleaning
    , spell_core_hrg
    , core_hrg_version_calculated
    , grouping_algorithm_version
    , unbundled_hrg_1
    , unbundled_hrg_2
    , unbundled_hrg_3
    , unbundled_hrg_4
    , unbundled_hrg_5
    , unbundled_hrg_6
    , unbundled_hrg_7
    , unbundled_hrg_8
    , unbundled_hrg_9
    , unbundled_hrg_10
    , unbundled_hrg_11
    , unbundled_hrg_12
    , spell_programme_budgeting_category
    , pb_r_spell_error_status
    , applicable_date
    , extract_date
    , spell_npoc
    , spell_service_line
    , cds_schema_version
    , prime_recipient
    , copy_recipients
    , derived_commissioner
    , derived_commissioner_type
    , unnamed_field
    , evidence_based_intervention_category
    , evidence_based_intervention_type
    , activity_period
from {{ ref('raw_sus_ip_monthly_pbr_preprocess_sp_daterange') }}
