{{ config(materialized='view') }}

select
    sk_encounter_id
    , dv_extract_type
    , dv_query_id
    , dv_fin_year
    , dv_fin_month
    , dv_activity_period_date
    , dv_month_at_end_activity
    , generated_record_id
    , attendance_identifier
    , spell_identifier
    , unique_cds_identifier
    , referrer_code
    , referring_organisation_code
    , referral_request_received_date
    , priority_type
    , service_type_requested
    , source_of_referral_for_outpatients
    , is_valid_ubrn
    , ubrn_occurrence_count
    , organisation_code_patient_pathway_identifier
    , rtt_patient_pathway_identifier
    , rtt_period_start_date
    , rtt_period_end_date
    , dv_rtt_length_derived
    , rtt_status
    , appointment_date
    , appointment_time
    , dv_cds_activity_date
    , administrative_category
    , first_attendance
    , attended_or_did_not_attend
    , outcome_of_attendance
    , consultant_code
    , medical_staff_type_seeing_patient
    , location_type_code
    , sk_patient_id
    , dw_nhs_number
    , ccg_nhs_number
    , local_patient_identifier
    , ethnic_category_code
    , age
    , dv_year_of_birth
    , gender_code
    , postcode_of_usual_address
    , dv_lsoa
    , gp_code
    , gp_practice_code_original_data
    , gp_practice_code_derived
    , dv_practice_code_validated
    , provider_reference_no
    , commissioner_reference_no
    , commissioning_serial_no_agreement_no
    , nhs_service_agreement_line_no
    , main_specialty_code
    , treatment_function_code
    , local_sub_specialty_code
    , clinic_code
    , dv_spec_com_service_code_national
    , dv_spec_com_service_code_local
    , spell_npoc
    , organisation_code_code_of_provider
    , site_code_of_treatment
    , organisation_code_pct_of_residence
    , patient_postcode_derived_pct
    , organisation_code_code_of_commissioner
    , pct_derived_from_gp_practice
    , dv_ccam_swl
    , dv_commissioner_code_of_residence
    , dv_purchaser_id
    , dv_contract_suffix
    , dv_cost_method_description
    , core_hrg
    , dv_hrg_used_for_tariff
    , dv_hrg
    , dv_local_cost_code
    , dv_reason_for_difference
    , spell_in_pb_r_not_in_pb_r
    , dv_is_pbr
    , dv_applicable_tariff
    , dv_base_cost
    , dv_tariff_type
    , dv_mff_index_applied
    , tariff_initial_amount_national
    , tariff_pre_mff_adjusted_national
    , tariff_total_payment_national
    , pbr_final_tariff
    , dv_total_cost_inc_mff
    , number_diagnosis
    , primary_diagnosis_code
    , secondary_diagnosis_code_1
    , secondary_diagnosis_code_2
    , secondary_diagnosis_code_3
    , secondary_diagnosis_code_4
    , secondary_diagnosis_code_5
    , secondary_diagnosis_code_6
    , secondary_diagnosis_code_7
    , secondary_diagnosis_code_8
    , secondary_diagnosis_code_9
    , secondary_diagnosis_code_10
    , secondary_diagnosis_code_11
    , secondary_diagnosis_code_12
    , operation_status
    , number_procedures
    , primary_procedure_code
    , primary_procedure_date
    , secondary_procedure_code_1
    , secondary_procedure_date_1
    , secondary_procedure_code_2
    , secondary_procedure_date_2
    , secondary_procedure_code_3
    , secondary_procedure_date_3
    , secondary_procedure_code_4
    , secondary_procedure_date_4
    , secondary_procedure_code_5
    , secondary_procedure_date_5
    , secondary_procedure_code_6
    , secondary_procedure_date_6
    , secondary_procedure_code_7
    , secondary_procedure_date_7
    , secondary_procedure_code_8
    , secondary_procedure_date_8
    , secondary_procedure_code_9
    , secondary_procedure_date_9
    , secondary_procedure_code_10
    , secondary_procedure_date_10
    , secondary_procedure_code_11
    , secondary_procedure_date_11
    , secondary_procedure_code_12
    , secondary_procedure_date_12
    , dv_unbundled_hrg_1
    , dv_unbundled_hrg_2
    , dv_unbundled_hrg_3
    , dv_unbundled_hrg_4
    , dv_unbundled_hrg_5
    , dv_unbundled_hrg_6
    , dv_unbundled_hrg_7
    , dv_unbundled_hrg_8
    , dv_unbundled_hrg_9
    , dv_unbundled_hrg_10
    , dv_unbundled_hrg_11
    , dv_unbundled_hrg_12
    , dv_number_unbundled_hr_gs
    , dv_number_unbundled_non_priced_hr_gs
    , dv_number_unbundled_priced_hr_gs
from {{ ref('raw_sus_op_monthly_encounterdenormalised_daterange') }}
