{{ config(materialized='view') }}

select
    sk_encounter_id
    , dv_extract_type
    , dv_query_id
    , dv_fin_year
    , dv_fin_month
    , dv_activity_period_date
    , generated_record_id
    , spell_identifier
    , unique_cds_identifier
    , hospital_provider_spell_no
    , referrer_code
    , referring_organisation_code
    , organisation_code_patient_pathway_identifier
    , rtt_patient_pathway_identifier
    , rtt_period_end_date
    , rtt_period_start_date
    , dv_rtt_length_derived
    , rtt_status
    , decided_to_admit_date
    , episode_start_date
    , episode_end_date
    , dv_episode_gross_length_of_stay
    , episode_number
    , last_episode_in_spell_indicator
    , start_date_hospital_provider_spell
    , start_time_hospital_provider_spell
    , end_date_hospital_provider_spell
    , discharge_time_hospital_provider_spell
    , ready_for_discharge_date
    , dv_length_of_stay_gross
    , dv_cds_activity_date
    , source_of_admission_hospital_provider_spell
    , discharge_destination_hospital_provider_spell
    , discharge_method_hospital_provider_spell
    , administrative_category_on_admission
    , first_regular_day_night_admission
    , intended_management
    , patient_classification
    , admission_method_hospital_provider_spell
    , age_group_intended_at_epiend
    , neonatal_level_of_care
    , dv_number_diagnoses
    , dv_number_procedures
    , dv_number_unbundled_hr_gs
    , sk_patient_id
    , dw_nhs_number
    , ccg_nhs_number
    , local_patient_identifier
    , carer_support_indicator
    , ethnic_category_code
    , age_at_cds_activity_date
    , birth_date
    , dv_year_of_birth
    , gender_code
    , postcode_of_usual_address
    , dv_lsoa_code
    , legal_status_classification_code
    , gp_code_original_data
    , gp_practice_code_original_data
    , gp_practice_code_derived
    , dv_practice_code_validated
    , provider_reference_no
    , commissioner_reference_no
    , commissioner_serial_no_agreement_no
    , nhs_service_agreement_line_no
    , consultant_code
    , main_specialty_code
    , treatment_function_code
    , local_sub_specialty_code
    , ward_code_at_episode_start_date
    , ward_code_at_episode_end_date
    , dv_ward_code_at_admission
    , dv_ward_code_at_discharge
    , dv_spec_com_service_code_national_episode
    , dv_spec_com_service_code_national_spell
    , dv_spec_com_service_code_local_episode
    , dv_spec_com_service_code_local_spell
    , organisation_code_code_of_provider
    , organisation_code_code_of_commissioner
    , site_code_of_treatment_at_start_of_episode
    , organisation_code_pct_of_residence
    , commissioner_code_original_data
    , pct_derived_from_gp_practice
    , patient_postcode_derived_pct
    , dv_ccam_sel
    , dv_ccam_swl
    , dv_commissioner_code_of_residence
    , dv_purchaser_id
    , dv_contract_suffix
    , dv_cost_method_description
    , programme_budgeting_category
    , core_hrg_calculated
    , spell_core_hrg
    , dv_hrg
    , dv_local_cost_code
    , dv_reason_for_difference
    , spell_in_pbr_not_in_pbr
    , dv_is_pbr
    , dv_applicable_tariff
    , dv_base_cost
    , dv_is_short_stay
    , dv_special_service_id
    , dv_service_adjustment_cost
    , dv_best_practice_tariff_code
    , dv_specialist_palliative_care_days
    , dv_rehab_days
    , dv_delayed_discharge_days
    , dv_tariff_type
    , dv_length_of_stay_net
    , dv_excess_bed_days
    , dv_excess_bed_days_cost
    , dv_mff_index_applied
    , pbr_final_tariff
    , dv_total_cost_inc_mff
    , primary_diagnosis_code
    , dv_is_spell
    , secondary_diagnosis_code_1
    , secondary_diagnosis_code_2
    , secondary_diagnosis_code_3
    , secondary_diagnosis_code_4
    , secondary_diagnosis_code_5
    , secondary_diagnosis_code_6
    , secondary_diagnosis_code_7
    , secondary_diagnosis_code_8
    , secondary_diagnosis_code_9
    , secondary_diagnosis_code_10
    , secondary_diagnosis_code_11
    , secondary_diagnosis_code_12
    , operation_status
    , primary_procedure_code
    , primary_procedure_date
    , secondary_procedure_code_1
    , secondary_procedure_date_1
    , secondary_procedure_code_2
    , secondary_procedure_date_2
    , secondary_procedure_code_3
    , secondary_procedure_date_3
    , secondary_procedure_code_4
    , secondary_procedure_date_4
    , secondary_procedure_code_5
    , secondary_procedure_date_5
    , secondary_procedure_code_6
    , secondary_procedure_date_6
    , secondary_procedure_code_7
    , secondary_procedure_date_7
    , secondary_procedure_code_8
    , secondary_procedure_date_8
    , secondary_procedure_code_9
    , secondary_procedure_date_9
    , secondary_procedure_code_10
    , secondary_procedure_date_10
    , secondary_procedure_code_11
    , secondary_procedure_date_11
    , secondary_procedure_code_12
    , secondary_procedure_date_12
    , dv_unbundled_hrg_1
    , dv_unbundled_hrg_2
    , dv_unbundled_hrg_3
    , dv_unbundled_hrg_4
    , dv_unbundled_hrg_5
    , dv_unbundled_hrg_6
    , dv_unbundled_hrg_7
    , dv_unbundled_hrg_8
    , dv_unbundled_hrg_9
    , dv_unbundled_hrg_10
    , dv_unbundled_hrg_11
    , dv_unbundled_hrg_12
    , dv_unbundled_days_total
    , dv_unbundled_cost_total
    , dv_critical_care_day_count
from {{ ref('raw_sus_ip_monthly_encounterdenormalised_daterange') }}
